# include "errno.h"
int errno = 0;
mdl_u8_t ffly_errno = FF_ERR_NULL;
char const static *s[] = {
	"okay",
	"operation not permitted",
	"no such file or directory",
	"no such process",
	"interrupted system call",
	"i/o error",
	"no such device or address",
	"argument list too long",
	"exec format error",
	"bad file number",
	"no child processes",
	"try again",
	"out of memory",
	"permission denied",
	"bad address",
	"block device required",
	"device or resource busy",
	"file exists",
	"cross-device link",
	"no such device",
	"not a directory",
	"is a directory",
	"invalid argument",
	"file table overflow",
	"too many open files",
	"not a typewriter",
	"text file busy",
	"file too large",
	"no space left on device",
	"illegal seek",
	"read-only file system",
	"too many links",
	"broken pipe",
	"math argument out of domain of func",
	"math result not representable",
	"resource deadlock would occur",
	"file name too long",
	"no record locks available",
	"invalid system call number",
	"directory not empty",
	"too many symbolic links encountered",
	"operation would block",
	"no message of desired type",
	"identifier removed",
	"channel number out of range",
	"level 2 not synchronized",
	"level 3 halted",
	"level 3 reset",
	"link number out of range",
	"protocol driver not attached",
	"no CSI structure available",
	"level 2 halted",
	"invalid exchange",
	"invalid request descriptor",
	"exchange full",
	"no anode",
	"invalid request code",
	"invalid slot",
	"58",
	"bad font file format",
	"device not a stream",
	"no data available",
	"timer expired",
	"out of streams resources",
	"machine is not on the network",
	"package not installed",
	"object is remote",
	"link has been severed",
	"advertise error",
	"srmount error",
	"communication error on send",
	"protocol error",
	"multihop attempted",
	"rfs specific error",
	"not a data message",
	"value too large for defined data type",
	"name not unique on network",
	"file descriptor in bad state",
	"remote address changed",
	"can not access a needed shared library"
};

char const* strerror(int __no) {
	int unsigned no = (__no^~0)+1;
	if (no >= (sizeof(s)/sizeof(char const*))) return "unknown";
	return s[no];
}

void set_errno() {
	__asm__("mov %%eax, %0" : "=m"(errno) :);
}
