# ifndef __ffly__nt__memalloc__h
# define __ffly__nt__memalloc__h
# include "../memory/mem_alloc.h"
# include "../memory/mem_free.h"
# include "../memory/mem_realloc.h"
#define nt_mem_alloc __ffly_mem_alloc
#define nt_mem_free __ffly_mem_free
#define nt_mem_realloc __ffly_mem_realloc
# endif /*__ffly__nt__memalloc__h*/
