# ifndef __ffly__checksum__h
# define __ffly__checksum__h
# include "../../ffint.h"
ff_u32_t ffly_bsd_cksum32(void*, ff_uint_t);
ff_u64_t ffly_bsd_cksum64(void*, ff_uint_t);
ff_u64_t ffly_ff_cksum64(void*, ff_uint_t);
ff_u32_t ffly_cksum32(void*, ff_uint_t);
ff_u64_t ffly_cksum64(void*, ff_uint_t);
# endif /*__ffly__checksum__h*/
