# ifndef __ffly__checksum__h
# define __ffly__checksum__h
# include <mdlint.h>
mdl_u32_t ffly_bsd_cksum32(void*, mdl_uint_t);
mdl_u64_t ffly_bsd_cksum64(void*, mdl_uint_t);
mdl_u64_t ffly_mdl_cksum64(void*, mdl_uint_t);
mdl_u32_t ffly_cksum32(void*, mdl_uint_t);
mdl_u64_t ffly_cksum64(void*, mdl_uint_t);
# endif /*__ffly__checksum__h*/
