# ifndef __ffly__shell__h
# define __ffly__shell__h
# include "shell/parser.h"
# include "shell/eval.h"
# include "shell/input.h"
# include "shell/lexer.h"
# include "shell/exec.h"
# include "shell/hash.h"
# include "shell/memalloc.h"
# endif /*__ffly__shell__h*/
